def translate_team(name):
    teams = {
        ' KTP': 'КТП',
        ' Warta poznan': 'Варта Познань',
        ' Warta poznań': 'Варта Познань',
        'AC Milan': 'AC Milan',
        'AC Oulu': 'AC Oulu',
        'AEK': 'АЕК',
        'AFC Wimbledon': 'Уимблдон',
        'AS Roma': 'AS Roma',
        'AVS': 'AVS',
        'AZ Alkmaar': 'АЗ',
        'Aberdeen': 'Абердин',
        'Accrington': 'Аккрингтон',
        'Ad. Demirspor': 'Ad. Demirspor',
        'Airdrie Utd': 'Airdrie Utd',
        'Ajaccio': 'Аяччо',
        'Ajax': 'Аякс',
        'Akhmat Grozny': 'Akhmat Grozny',
        'Akron Togliatti': 'Akron Togliatti',
        'Alanyaspor': 'Аланьяспор',
        'Alaves': 'Алавес',
        'Albacete': 'Альбасете',
        'Albion Rvs': 'Albion Rvs',
        'Alcorcon': 'Алькоркон',
        'Aldershot': 'Aldershot',
        'Alessandria': 'Алессандрия',
        'Alloa': 'Аллоа',
        'Almere City': 'Алмере Сити',
        'Almeria': 'Альмерия',
        'Altay': 'Altay',
        'Altrincham': 'Altrincham',
        'Alverca': 'Alverca',
        'Amiens': 'Амьен',
        'Amkar': 'Amkar',
        'Amorebieta': 'Amorebieta',
        'Anderlecht': 'Андерлехт',
        'Andorra': 'Андорра',
        'Angers': 'Анже',
        'Ankaragucu': 'Анкарагюджю',
        'Annan Athletic': 'Annan Athletic',
        'Annecy': 'Анси',
        'Antalyaspor': 'Антальяспор',
        'Antwerp': 'Антверпен',
        'Apollon': 'Apollon',
        'Arbroath': 'Арброт',
        'Aris': 'Арис',
        'Arka Gdynia': 'Arka Gdynia',
        'Arouca': 'Ароука',
        'Arsenal': 'Арсенал',
        'Arsenal Tula': 'Арсенал Тула',
        'Ascoli': 'Асколи',
        'Asteras Tripolis': 'Астерас',
        'Aston Villa': 'Астон Вилла',
        'Atalanta': 'Аталанта',
        'Atalanta BC': 'Atalanta BC',
        'Ath Bilbao': 'Атлетик',
        'Ath Madrid': 'Атлетико',
        'Athens Kallithea': 'Athens Kallithea',
        'Atromitos': 'Атромитос',
        'Augsburg': 'Аугсбург',
        'Auxerre': 'Осер',
        'Ayr': 'Эйр',
        'Baltika': 'Балтика',
        'Barcelona': 'Барселона',
        'Bari': 'Бари',
        'Barnet': 'Barnet',
        'Barnsley': 'Барнсли',
        'Barrow': 'Барроу',
        'Bastia': 'Bastia',
        'Bayern Munich': 'Бавария',
        'Beerschot VA': 'Беерсхот',
        'Beijing Guoan': 'Beijing Guoan',
        'Beijing Renhe': 'Beijing Renhe',
        'Belenenses': 'Белененсеш',
        'Benevento': 'Беневенто',
        'Benfica': 'Бенфика',
        'Besiktas': 'Бешикташ',
        'Betis': 'Бетис',
        'Bielefeld': 'Арминия',
        'Birmingham': 'Бирмингем',
        'Blackburn': 'Блэкберн',
        'Blackpool': 'Блэкпул',
        'Boavista': 'Боавишта',
        'Bochum': 'Бохум',
        'Bodrumspor': 'Бодрумспор',
        'Bologna': 'Болонья',
        'Bolton': 'Болтон',
        'Bonnyrigg Rose': 'Bonnyrigg Rose',
        'Bordeaux': 'Бордо',
        'Boreham Wood': 'Boreham Wood',
        'Boston Utd': 'Boston Utd',
        'Bournemouth': 'Борнмут',
        'Bradford': 'Брэдфорд',
        'Braintree Town': 'Braintree Town',
        'Braunschweig': 'Айнтрахт Брауншвейг',
        'Brechin': 'Brechin',
        'Brentford': 'Брентфорд',
        'Brescia': 'Брешиа',
        'Brest': 'Брест',
        'Brighton': 'Брайтон',
        'Brighton and Hove Albion': 'Brighton and Hove Albion',
        'Bristol City': 'Бристоль Сити',
        'Bristol Rvs': 'Бристоль Роверс',
        'Bromley': 'Bromley',
        'Burgos': 'Бургос',
        'Burnley': 'Бернли',
        'Burton': 'Бертон',
        'Buyuksehyr': 'Buyuksehyr',
        'CSKA Moscow': 'ЦСКА Москва',
        'Cadiz': 'Кадис',
        'Caen': 'Кан',
        'Cagliari': 'Кальяри',
        'Cambridge': 'Кембридж',
        'Cambuur': 'Cambuur',
        'Cangzhou': 'Cangzhou',
        'Cardiff': 'Кардифф',
        'Carlisle': 'Карлайл',
        'Carrarese': 'Carrarese',
        'Cartagena': 'Картахена',
        'Casa Pia': 'Каса Пиа',
        'Castellon': 'Castellon',
        'Catanzaro': 'Катандзаро',
        'Celta': 'Сельта',
        'Celtic': 'Селтик',
        'Cercle Brugge': 'Серкль Брюгге',
        'Cesena': 'Cesena',
        'Chambly': 'Chambly',
        'Changchun Yatai': 'Changchun Yatai',
        'Charleroi': 'Шарлеруа',
        'Charlton': 'Чарльтон',
        'Chateauroux': 'Шатору',
        'Chaves': 'Шавиш',
        'Chelsea': 'Челси',
        'Cheltenham': 'Челтнем',
        'Chengdu Rongcheng': 'Chengdu Rongcheng',
        'Chesterfield': 'Chesterfield',
        'Chievo': 'Chievo',
        'Chongqing Liangjiang Athletic': 'Chongqing Liangjiang Athletic',
        'Chongqing Tonglianglong': 'Chongqing Tonglianglong',
        'Cittadella': 'Читтаделла',
        'Clermont': 'Клермон',
        'Club Brugge': 'Брюгге',
        'Clyde': 'Клайд',
        'Colchester': 'Колчестер',
        'Como': 'Комо',
        'Concarneau': 'Конкарно',
        'Cordoba': 'Cordoba',
        'Cosenza': 'Козенца',
        'Cove Rangers': 'Cove Rangers',
        'Coventry': 'Ковентри',
        'Coventry City': 'Coventry City',
        'Cowdenbeath': 'Кауденбит',
        'Cracovia': 'Cracovia',
        'Crawley Town': 'Crawley Town',
        'Cremonese': 'Кремонезе',
        'Crewe': 'Крю',
        'Crotone': 'Кротоне',
        'Crystal Palace': 'Кристал Пэлас',
        'Dag and Red': 'Dag and Red',
        'Dalian Pro': 'Dalian Pro',
        'Dalian Yifang F.C.': 'Dalian Yifang F.C.',
        'Dalian Yingbo': 'Dalian Yingbo',
        'Darmstadt': 'Дармштадт',
        'Den Haag': 'АДО Ден Хааг',
        'Dender': 'Дендер',
        'Denizlispor': 'Denizlispor',
        'Derby': 'Дерби Каунти',
        'Dijon': 'Дижон',
        'Doncaster': 'Донкастер',
        'Dorking': 'Dorking',
        'Dortmund': 'Боруссия Д',
        'Dover Athletic': 'Dover Athletic',
        'Dresden': 'Динамо Дрезден',
        'Dumbarton': 'Дамбартон',
        'Dundee': 'Dundee',
        'Dundee United': 'Dundee United',
        'Dunfermline': 'Данфермлин',
        'Dunkerque': 'Дюнкерк',
        'Dynamo Makhachkala': 'Dynamo Makhachkala',
        'Dynamo Moscow': 'Динамо Москва',
        'East Fife': 'Ист Файф',
        'Eastleigh': 'Eastleigh',
        'Ebbsfleet': 'Ebbsfleet',
        'Edinburgh City': 'Эдинбург Сити',
        'Eibar': 'Эйбар',
        'Ein Frankfurt': 'Айнтрахт',
        'Ekenas': 'Ekenas',
        'Elche': 'Эльче',
        'Eldense': 'Eldense',
        'Elgin': 'Элджин',
        'Elversberg': 'Эльверсберг',
        'Empoli': 'Эмполи',
        'Erzgebirge Aue': 'Erzgebirge Aue',
        'Erzurum BB': 'Erzurum BB',
        'Espanol': 'Эспаньол',
        'Estoril': 'Эшторил',
        'Estrela': 'Эштрела',
        'Eupen': 'Эйпен',
        'Everton': 'Эвертон',
        'Excelsior': 'Excelsior',
        'Exeter': 'Эксетер',
        'Eyupspor': 'Эюпспор',
        'FC Edinburgh': 'FC Edinburgh',
        'FC Emmen': 'FC Emmen',
        'FC Koln': 'Кёльн',
        'FK Anzi Makhackala': 'FK Anzi Makhackala',
        'FK Rostov': 'FK Rostov',
        'Fakel Voronezh': 'Fakel Voronezh',
        'Falkirk': 'Фалкирк',
        'Famalicao': 'Фамаликан',
        'Farense': 'Farense',
        'Fenerbahce': 'Фенербахче',
        'FeralpiSalo': 'Феральпи',
        'Ferrol': 'Ferrol',
        'Feyenoord': 'Фейеноорд',
        'Fiorentina': 'Фиорентина',
        'Fleetwood Town': 'Fleetwood Town',
        'For Sittard': 'For Sittard',
        'Forest Green': 'Форест Грин',
        'Forfar': 'Форфар',
        'Fortuna Dusseldorf': 'Fortuna Dusseldorf',
        'Freiburg': 'Фрайбург',
        'Frosinone': 'Фрозиноне',
        'Fuenlabrada': 'Фуэнлабрада',
        'Fulham': 'Фулхэм',
        'Fylde': 'Fylde',
        'GKS Belchatow': 'GKS Belchatow',
        'GKS Katowice': 'GKS Katowice',
        'Galatasaray': 'Галатасарай',
        'Gateshead': 'Gateshead',
        'Gaziantep': 'Газиантеп',
        'Genclerbirligi': 'Genclerbirligi',
        'Genk': 'Генк',
        'Genoa': 'Дженоа',
        'Gent': 'Гент',
        'Getafe': 'Хетафе',
        'Giannina': 'Giannina',
        'Gil Vicente': 'Жил Висенте',
        'Gillingham': 'Джиллингем',
        'Giresunspor': 'Giresunspor',
        'Girona': 'Жирона',
        'Gnistan': 'Gnistan',
        'Go Ahead Eagles': 'Гоу Эхед Иглз',
        'Gornik Z.': 'Gornik Z.',
        'Gornik Zabrze': 'Gornik Zabrze',
        'Goztep': 'Goztep',
        'Granada': 'Гранада',
        'Grenoble': 'Гренобль',
        'Greuther Furth': 'Greuther Furth',
        'Grimsby': 'Grimsby',
        'Groningen': 'Гронинген',
        'Guangzhou City': 'Guangzhou City',
        'Guangzhou Evergrande': 'Guangzhou Evergrande',
        'Guangzhou FC': 'Guangzhou FC',
        'Guangzhou R&F': 'Guangzhou R&F',
        'Guimaraes': 'Guimaraes',
        'Guingamp': 'Генгам',
        'Guizhou Zhicheng': 'Guizhou Zhicheng',
        'HIFK': 'HIFK',
        'HJK': 'HJK',
        'Haka': 'Haka',
        'Halifax': 'Halifax',
        'Hamburg': 'Гамбург',
        'Hamilton': 'Гамильтон',
        'Hangzhou Greentown': 'Hangzhou Greentown',
        'Hannover': 'Hannover',
        'Hansa Rostock': 'Ганза',
        'Harrogate': 'Харрогейт',
        'Hartlepool': 'Хартлпул',
        'Hatayspor': 'Хатайспор',
        'Hearts': 'Хартс',
        'Hebei': 'Hebei',
        'Heerenveen': 'Херенвен',
        'Heidenheim': 'Хайденхайм',
        'Henan Songshan Longmen': 'Henan Songshan Longmen',
        'Heracles': 'Хераклес',
        'Hertha': 'Герта Берлин',
        'Hibernian': 'Хиберниан',
        'Hoffenheim': 'Хоффенхайм',
        'Holstein Kiel': 'Хольштайн',
        'Honka': 'Honka',
        'Huddersfield': 'Хаддерсфилд',
        'Huesca': 'Уэска',
        'Hull': 'Халл Сити',
        'Hull City': 'Hull City',
        'Ibiza': 'Ibiza',
        'Ilves': 'Ilves',
        'Ingolstadt': 'Ингольштадт',
        'Inter': 'Интер Милан',
        'Inter Milan': 'Inter Milan',
        'Inter Turku': 'Inter Turku',
        'Inverness C': 'Inverness C',
        'Ionikos': 'Ионикос',
        'Ipswich': 'Ipswich',
        'Ipswich Town': 'Ipswich Town',
        'Istanbulspor': 'Istanbulspor',
        'JJK Jyvaskyla': 'JJK Jyvaskyla',
        'Jagiellonia': 'Jagiellonia',
        'Jaro': 'Jaro',
        'Jiangsu Suning': 'Jiangsu Suning',
        'Juve Stabia': 'Juve Stabia',
        'Juventus': 'Ювентус',
        'KPV Kokkola': 'KPV Kokkola',
        'KTP': 'KTP',
        'Kaiserslautern': 'Kaiserslautern',
        'Karagumruk': 'Карагюмрюк',
        'Karlsruhe': 'Karlsruhe',
        'Kasimpasa': 'Касымпаша',
        'Kayserispor': 'Кайсериспор',
        'Kelty Hearts': 'Kelty Hearts',
        'Khimki': 'Химки',
        'Kidderminster': 'Kidderminster',
        'Kifisia': 'Kifisia',
        'Kilmarnock': 'Килмарнок',
        'Kings Lynn': 'Kings Lynn',
        'Konyaspor': 'Коньяспор',
        'Korona Kielce': 'Korona Kielce',
        'Kortrijk': 'Кортрейк',
        'Krasnodar': 'Краснодар',
        'Krylya Sovetov': 'Крылья',
        'KuPS': 'KuPS',
        'Kuban': 'Kuban',
        'LKS Lodz': 'LKS Lodz',
        'La Coruna': 'La Coruna',
        'Lahti': 'Lahti',
        'Lamia': 'Ламия',
        'Larisa': 'Larisa',
        'Las Palmas': 'Лас-Пальмас',
        'Laval': 'Лаваль',
        'Lazio': 'Лацио',
        'Le Havre': 'Гавр',
        'Lecce': 'Лечче',
        'Lecco': 'Лекко',
        'Lech Poznan': 'Lech Poznan',
        'Lechia Gdansk': 'Lechia Gdansk',
        'Leczna': 'Leczna',
        'Leeds': 'Лидс',
        'Leeds United': 'Leeds United',
        'Leganes': 'Леганес',
        'Legia': 'Legia',
        'Legnica': 'Legnica',
        'Leicester': 'Лестер',
        'Lens': 'Ланс',
        'Levadeiakos': 'Levadeiakos',
        'Levante': 'Леванте',
        'Leverkusen': 'Leverkusen',
        'Leyton Orient': 'Лейтон Ориент',
        'Liaoning': 'Liaoning',
        'Liaoning Tieren': 'Liaoning Tieren',
        'Lille': 'Лилль',
        'Lincoln': 'Линкольн',
        'Liverpool': 'Ливерпуль',
        'Livingston': 'Ливингстон',
        'Logrones': 'Logrones',
        'Lokomotiv Moscow': 'Локомотив Москва',
        'Lorient': 'Лорьян',
        'Lugo': 'Луго',
        'Luton': 'Лутон',
        'Lyon': 'Лион',
        "M'gladbach": 'Боруссия М',
        'M. Saransk': 'M. Saransk',
        'Magdeburg': 'Магдебург',
        'Maidenhead': 'Maidenhead',
        'Maidstone': 'Maidstone',
        'Mainz': 'Майнц',
        'Malaga': 'Malaga',
        'Mallorca': 'Мальорка',
        'Man City': 'Ман Сити',
        'Man United': 'МЮ',
        'Manchester City': 'Manchester City',
        'Manchester United': 'Manchester United',
        'Mansfield': 'Мэнсфилд',
        'Mantova': 'Mantova',
        'Mariehamn': 'Mariehamn',
        'Maritimo': 'Маритиму',
        'Marseille': 'Марсель',
        'Martigues': 'Мартиг',
        'Mechelen': 'Мехелен',
        'Meizhou Hakka': 'Meizhou Hakka',
        'Metz': 'Мец',
        'Middlesbrough': 'Мидлсбро',
        'Milan': 'Милан',
        'Millwall': 'Миллуол',
        'Milton Keynes Dons': 'Milton Keynes Dons',
        'Mirandes': 'Мирандес',
        'Modena': 'Модена',
        'Monaco': 'Монако',
        'Montpellier': 'Монпелье',
        'Montrose': 'Монтроз',
        'Monza': 'Монца',
        'Morecambe': 'Моркам',
        'Moreirense': 'Морейренсе',
        'Morton': 'Мортон',
        'Motherwell': 'Мазервелл',
        'Motor Lublin': 'Motor Lublin',
        'Mouscron': 'Мускрон',
        'MyPa': 'MyPa',
        'NAC Breda': 'NAC Breda',
        'Nacional': 'Насьонал',
        'Nancy': 'Нанси',
        'Nantes': 'Нант',
        'Nantong Zhiyun': 'Nantong Zhiyun',
        'Napoli': 'Наполи',
        'Newcastle': 'Ньюкасл',
        'Newcastle United': 'Newcastle United',
        'Newport County': 'Newport County',
        'Nice': 'Ницца',
        'Nijmegen': 'НЕК Неймеген',
        'Nimes': 'Nimes',
        'Niort': 'Ньор',
        'Northampton': 'Нортгемптон',
        'Norwich': 'Норвич',
        "Nott'm Forest": 'Ноттингем Форест',
        'Nottingham Forest': 'Nottingham Forest',
        'Notts County': 'Notts County',
        'Nurnberg': 'Нюрнберг',
        'OFI Crete': 'ОФИ',
        'Oldham': 'Олдхэм',
        'Olympiakos': 'Олимпиакос',
        'Oostende': 'Остенде',
        'Orenburg': 'Оренбург',
        'Osasuna': 'Осасуна',
        'Osnabruck': 'Osnabruck',
        'Oud-Heverlee Leuven': 'Лёвен',
        'Oviedo': 'Овьедо',
        'Oxford': 'Оксфорд',
        'Oxford City': 'Oxford City',
        'PAOK': 'ПАОК',
        'PK-35 Vantaa': 'PK-35 Vantaa',
        'PS Kemi': 'PS Kemi',
        'PSV Eindhoven': 'ПСВ',
        'Pacos Ferreira': 'Пасуш де Феррейра',
        'Paderborn': 'Падерборн',
        'Palermo': 'Палермо',
        'Panathinaikos': 'Панатинаикос',
        'Panetolikos': 'Панетоликос',
        'Panserraikos': 'Пансерраикос',
        'Pari NN': 'Pari NN',
        'Paris FC': 'Paris FC',
        'Paris SG': 'ПСЖ',
        'Parma': 'Парма',
        'Partick': 'Партик',
        'Pau FC': 'Pau FC',
        'Pendikspor': 'Пендикспор',
        'Perugia': 'Перуджа',
        'Pescara': 'Pescara',
        'Peterboro': 'Питерборо',
        'Peterhead': 'Питерхед',
        'Piast Gliwice': 'Piast Gliwice',
        'Pisa': 'Пиза',
        'Plymouth': 'Плимут',
        'Podbeskidzie': 'Podbeskidzie',
        'Pogon Szczecin': 'Pogon Szczecin',
        'Polonia Warszawa': 'Polonia Warszawa',
        'Ponferradina': 'Понферрадина',
        'Pordenone': 'Pordenone',
        'Port Vale': 'Порт Вейл',
        'Portimonense': 'Портимоненсе',
        'Porto': 'Порту',
        'Portsmouth': 'Портсмут',
        'Preston': 'Престон',
        'Preußen Münster': 'Preußen Münster',
        'Puszcza': 'Puszcza',
        'QPR': 'Куинз Парк Рейнджерс',
        'Qingdao FC': 'Qingdao FC',
        'Qingdao Hainiu': 'Qingdao Hainiu',
        'Qingdao West Coast': 'Qingdao West Coast',
        'Queen of Sth': 'Queen of Sth',
        'Queens Park': 'Queens Park',
        'Quevilly Rouen': 'Quevilly Rouen',
        'R. Volgograd': 'R. Volgograd',
        'RB Leipzig': 'РБ Лейпциг',
        'RWD Molenbeek': 'RWD Molenbeek',
        'Radomiak Radom': 'Radomiak Radom',
        'Raith Rvs': 'Raith Rvs',
        'Rakow': 'Rakow',
        'Rangers': 'Рейнджерс',
        'Reading': 'Рединг',
        'Real Madrid': 'Реал Мадрид',
        'Red Star': 'Red Star',
        'Regensburg': 'Регенсбург',
        'Reggiana': 'Reggiana',
        'Reggina': 'Реджина',
        'Reims': 'Реймс',
        'Rennes': 'Ренн',
        'Rio Ave': 'Риу Аве',
        'Rizespor': 'Ризеспор',
        'Rochdale': 'Рочдейл',
        'Rodez': 'Родез',
        'Roma': 'Рома',
        'Ross County': 'Росс Каунти',
        'Rotherham': 'Ротерхэм',
        'Rovaniemi': 'Rovaniemi',
        'Rubin Kazan': 'Рубин Казань',
        'Ruch': 'Ruch',
        'Ruch Chorzow': 'Ruch Chorzow',
        'SJK': 'SJK',
        'SKA Khabarovsk': 'СКА Хабаровск',
        'Sabadell': 'Сабадель',
        'Salernitana': 'Салернитана',
        'Salford': 'Солфорд',
        'Sampdoria': 'Сампдория',
        'Samsunspor': 'Самсунспор',
        'Sandecja Nowy S.': 'Sandecja Nowy S.',
        'Sandhausen': 'Зандхаузен',
        'Santa Clara': 'Санта-Клара',
        'Santander': 'Santander',
        'Sassuolo': 'Сассуоло',
        'Schalke 04': 'Шальке',
        'Scunthorpe': 'Сканторп',
        'Seraing': 'Seraing',
        'Sevilla': 'Севилья',
        'Shandong Luneng': 'Shandong Luneng',
        'Shandong Taishan': 'Shandong Taishan',
        'Shanghai Port': 'Shanghai Port',
        'Shanghai SIPG': 'Shanghai SIPG',
        'Shanghai Shenhua': 'Shanghai Shenhua',
        'Shanghai Shenxin': 'Shanghai Shenxin',
        'Sheffield United': 'Шеффилд Юнайтед',
        'Sheffield Weds': 'Sheffield Weds',
        'Shenzhen': 'Shenzhen',
        'Shenzhen Xinpengcheng': 'Shenzhen Xinpengcheng',
        'Shijiazhuang': 'Shijiazhuang',
        'Shrewsbury': 'Шрусбери',
        'Sivasspor': 'Сивасспор',
        'Slask Wroclaw': 'Slask Wroclaw',
        'Sochaux': 'Сошо',
        'Sochi': 'Сочи',
        'Sociedad': 'Sociedad',
        'Sociedad B': 'Sociedad B',
        'Solihull': 'Solihull',
        'Southampton': 'Саутгемптон',
        'Southend': 'Southend',
        'Sp Braga': 'Брага',
        'Sp Gijon': 'Sp Gijon',
        'Sp Lisbon': 'Спортинг',
        'Spal': 'СПАЛ',
        'Sparta Rotterdam': 'Спарта Роттердам',
        'Spartak Moscow': 'Спартак Москва',
        'Spartak Nalchik': 'Спартак Нальчик',
        'Spartans': 'Spartans',
        'Spezia': 'Специя',
        'St Etienne': 'Сент-Этьен',
        'St Johnstone': 'Сент-Джонстон',
        'St Mirren': 'Сент-Миррен',
        'St Pauli': 'Санкт-Паули',
        'St Truiden': 'Сент-Трюйден',
        'St. Gilloise': 'St. Gilloise',
        'Stal Mielec': 'Stal Mielec',
        'Standard': 'Стандард',
        'Stenhousemuir': 'Стенхаусмур',
        'Stevenage': 'Стивенидж',
        'Stirling': 'Stirling',
        'Stockport': 'Stockport',
        'Stoke': 'Сток Сити',
        'Stranraer': 'Странрар',
        'Strasbourg': 'Страсбур',
        'Stuttgart': 'Штутгарт',
        'Sudtirol': 'Зюдтироль',
        'Sunderland': 'Сандерленд',
        'Sutton': 'Саттон',
        'Swansea': 'Суонси',
        'Swindon': 'Суиндон',
        'T. Moscow': 'T. Moscow',
        'TPS': 'TPS',
        'Tambov': 'Тамбов',
        'Tamworth': 'Tamworth',
        'Tenerife': 'Тенерифе',
        'Termalica B-B.': 'Termalica B-B.',
        'Ternana': 'Тернана',
        'Tianjin Jinmen Tiger': 'Tianjin Jinmen Tiger',
        'Tianjin Quanjian': 'Tianjin Quanjian',
        'Tianjin Tianhai': 'Tianjin Tianhai',
        'Tomsk': 'Томь',
        'Tondela': 'Тондела',
        'Torino': 'Торино',
        'Torpedo Moscow': 'Торпедо',
        'Torquay': 'Torquay',
        'Tosno': 'Тосно',
        'Tottenham': 'Тоттенхэм',
        'Tottenham Hotspur': 'Tottenham Hotspur',
        'Toulouse': 'Тулуза',
        'Trabzonspor': 'Трабзонспор',
        'Tranmere': 'Транмир',
        'Troyes': 'Труа',
        'Twente': 'Twente',
        'Udinese': 'Удинезе',
        'Ufa': 'Уфа',
        'Ulm': 'Ulm',
        'Umraniyespor': 'Umraniyespor',
        'Union Berlin': 'Унион Берлин',
        'Ural': 'Урал',
        'Utrecht': 'Утрехт',
        'VPS': 'VPS',
        'VVV Venlo': 'VVV Venlo',
        'Valencia': 'Валенсия',
        'Valenciennes': 'Valenciennes',
        'Valladolid': 'Вальядолид',
        'Vallecano': 'Vallecano',
        'Venezia': 'Венеция',
        'Verona': 'Верона',
        'Vicenza': 'Виченца',
        'Villarreal': 'Вильярреал',
        'Villarreal B': 'Villarreal B',
        'Virtus Entella': 'Virtus Entella',
        'Vitesse': 'Витесс',
        'Vizela': 'Визела',
        'Vladikavkaz': 'Vladikavkaz',
        'Volendam': 'Volendam',
        'Volga N. Novgorod': 'Volga N. Novgorod',
        'Volgar-Astrakhan': 'Volgar-Astrakhan',
        'Volos NFC': 'Volos NFC',
        'Waalwijk': 'Валвейк',
        'Waasland-Beveren': 'Васланд-Беверен',
        'Walsall': 'Уолсолл',
        'Waregem': 'Зюлте Варегем',
        'Warta Poznan': 'Warta Poznan',
        'Watford': 'Уотфорд',
        'Wealdstone': 'Wealdstone',
        'Wehen': 'Вен',
        'Werder Bremen': 'Вердер Бремен',
        'West Brom': 'Вест Бромвич',
        'West Ham': 'Вест Хэм',
        'Westerlo': 'Вестерло',
        'Weymouth': 'Weymouth',
        'Widzew Lodz': 'Widzew Lodz',
        'Wigan': 'Уиган',
        'Willem II': 'Виллем II',
        'Wisla': 'Wisla',
        'Wisla Plock': 'Wisla Plock',
        'Woking': 'Woking',
        'Wolfsburg': 'Вольфсбург',
        'Wolves': 'Вулверхэмптон',
        'Wrexham': 'Wrexham',
        'Wuhan FC': 'Wuhan FC',
        'Wuhan Three Towns': 'Wuhan Three Towns',
        'Wurzburger Kickers': 'Wurzburger Kickers',
        'Wycombe': 'Уиком',
        'Yanbian': 'Yanbian',
        'Yeni Malatyaspor': 'Yeni Malatyaspor',
        'Yenisey': 'Енисей',
        'Yeovil': 'Yeovil',
        'York': 'York',
        'Yunnan Yukun': 'Yunnan Yukun',
        'Zaglebie': 'Zaglebie',
        'Zaglebie Sosnowiec': 'Zaglebie Sosnowiec',
        'Zaragoza': 'Сарагоса',
        'Zawisza': 'Zawisza',
        'Zenit': 'Зенит',
        'Zhejiang Greentown': 'Zhejiang Greentown',
        'Zhejiang Professional': 'Zhejiang Professional',
        'Zhejiang Yiteng': 'Zhejiang Yiteng',
        'Zwolle': 'Зволле',
        'aberdeen': 'Абердин',
        'ac milan': 'Милан',
        'academica': 'Академика',
        'academica coimbra': 'Академика Коимбра',
        'academico viseu': 'Академику Визеу',
        'académico de viseu': 'Академику Визеу',
        'aek athens': 'АЕК Афины',
        'aek athens fc': 'АЕК Афины',
        'ajax': 'Аякс',
        'alanyaspor': 'Аланьяспор',
        'anderlecht': 'Андерлехт',
        'antalyaspor': 'Антальяспор',
        'antwerp': 'Антверпен',
        'aris': 'Арис',
        'aris thessaloniki': 'Арис Салоники',
        'arsenal': 'Арсенал',
        'asteras tripoli': 'Астерас Триполи',
        'asteras tripolis': 'Астерас Триполис',
        'atletico madrid': 'Атлетико Мадрид',
        'atromitos': 'Атромитос',
        'atromitos athens': 'Атромитос Афины',
        'av es': 'Авеш',
        'avess': 'Авеш',
        'barcelona': 'Барселона',
        'basaksehir': 'Башакшехир',
        'bayern': 'Бавария',
        'bayern (amateurs)': 'Бавария люб.',
        'bayern munich': 'Бавария',
        'belgrade adelaide': 'Белград Аделаида',
        'benfica': 'Бенфика',
        'besiktas': 'Бешикташ',
        'beşiktaş': 'Бешикташ',
        'boavista': 'Боавишта',
        'boavista fc': 'Боавишта',
        'bodrumspor': 'Бодрумспор',
        'borondara eagles (w)': 'Борундара Иглс ж',
        'borussia (amateurs)': 'Боруссия люб.',
        'borussia dortmund': 'Боруссия Дортмунд',
        'box hill united (w)': 'Бокс Хилл Юнайтед ж',
        'braga': 'Брага',
        'brisbane city': 'Брисбен Сити',
        'brisbane olympic (u23)': 'Брисбен Олимпик до23',
        'brisbane roar (youth)': 'Брисбен Роар мол.',
        'brisbane strikers': 'Брисбен Страйкерс',
        'broadbeach united (u23)': 'Бродбич Юнайтед до23',
        'campbelltown city': 'Кемпбелтаун Сити',
        'canberra white eagles': 'Канберра Уайт Иглз',
        'canterbury bankstown': 'Кантербери Банкстоун',
        'capalaba (u23)': 'Капалаба до23',
        'capalaba fc': 'Капалаба ФК',
        'caroline springs george cross (u23)': 'Каролайн Спрингс до23',
        'casa pia': 'Каза Пия',
        'casa pia ac': 'Каза Пия',
        'cd feirense': 'Фейренсе',
        'cd mafra': 'Мафра',
        'cd nacional': 'Насьонал',
        'cd tondela': 'Тондела',
        'cd trofense': 'Трофенсе',
        'celtic': 'Селтик',
        'central coast mariners (youth)': 'Централ Коаст Маринерс мол.',
        'cercle brugge': 'Серкль Брюгге',
        'cercle brugge ksv': 'Серкль Брюгге',
        'cf estrela': 'Эштрела',
        'cf estrela amadora': 'Эштрела Амадора',
        'charleroi': 'Шарлеруа',
        'chaves': 'Шавеш',
        'chelsea': 'Челси',
        'club brugge': 'Брюгге',
        'club brugge kv': 'Брюгге',
        'covilha': 'Ковильян',
        'cracovia krakow': 'Краковия Краков',
        'cracovia kraków': 'Краковия Краков',
        'cs maritimo': 'Маритиму',
        'dulwich hill': 'Далвич Хилл',
        'dundee fc': 'Данди ФК',
        'dundee united': 'Данди Юнайтед',
        'eastern suburbs': 'Истерн Сабёрбс',
        'eastern suburbs (u23)': 'Истерн Сабёрбс до23',
        'estoril': 'Эшторил',
        'estrela': 'Эштрела',
        'estrela amadora': 'Эштрела Амадора',
        'eyupspor': 'Эюпспор',
        'eyüpspor': 'Эюпспор',
        'fafe': 'Фафе',
        'famalicao': 'Фамаликан',
        'farense': 'Фаренсе',
        'fatih karagumruk': 'Фатих Карагюмрюк',
        'fc KTP': 'ФК КТП',
        'fc barcelona': 'Барселона',
        'fc bayern munchen': 'Бавария',
        'fc famalicao': 'Фамаликан',
        'fc haka': 'ФК Хака',
        'fc lahti': 'ФК Лахти',
        'fc moreirense': 'Морейренсе',
        'fc pacos ferreira': 'Пасуш де Феррейра',
        'fc penafiel': 'Пенафиел',
        'fc porto': 'Порту',
        'feirense': 'Фейренсе',
        'fenerbahce': 'Фенербахче',
        'fenerbahçe': 'Фенербахче',
        'feyenoord': 'Фейеноорд',
        'fraport taw antalyaspor': 'Фрапорт Тав Антальяспор',
        'galatasaray': 'Галатасарай',
        'gaziantep fk': 'Газиантеп ФК',
        'gd chaves': 'Шавеш',
        'gd estoril praia': 'Эшторил',
        'genk': 'Генк',
        'gent': 'Гент',
        'gil vicente': 'Жил Висенте',
        'gil vicente fc': 'Жил Висенте',
        'giresunspor': 'Гиресунспор',
        'gnistan': 'Гнистан',
        'gold coast knights': 'Голд Кост Найтс',
        'gor nik zabrze': 'Гурник Забже',
        'gor zabrze': 'Гурник Забже',
        'haka': 'Хака',
        'hatayspor': 'Хатайспор',
        'heart of midlothian': 'Харт оф Мидлотиан',
        'hearts': 'Хартс',
        'heidelberg united (w)': 'Хейдельберг Юнайтед ж',
        'henderson (w)': 'Хендэ ж',
        'hibernian': 'Хиберниан',
        'hibs': 'Хибс',
        'hills united brumbies': 'Хиллс Юнайтед Брамбис',
        'hjk': 'ХИК',
        'hjk helsinki': 'ХИК Хельсинки',
        'honka': 'Хонка',
        'honka espoo': 'Хонка Эспоо',
        'hurstville': 'Херствиль',
        'if gnistan': 'ИФ Гнистан',
        'ifk mariehamn': 'ИФК Мариехамн',
        'ilves': 'Ильвес',
        'ilves tampere': 'Ильвес Тампере',
        'inter lions': 'Интер Лайонс',
        'inter milan': 'Интер',
        'inter turku': 'Интер Турку',
        'ipswich knights': 'Ипсвич Найтс',
        'istanbulspor': 'Стамбулспор',
        'jagiellonia bialystok': 'Ягеллония Белосток',
        'jagiellonia białystok': 'Ягеллония Белосток',
        'juventus': 'Ювентус',
        'kaa gent': 'Гент',
        'kasimpasa': 'Касымпаша',
        'kasimpaşa': 'Касымпаша',
        'kayserispor': 'Кайсериспор',
        'kifisia': 'Кифисья',
        'kilmarnock': 'Килмарнок',
        'konyaspor': 'Коньяспор',
        'korona kielce': 'Корона Кельце',
        'kortrijk': 'Кортрейк',
        'kups': 'КуПС',
        'kups kuopio': 'КуПС Куопио',
        'kv kortrijk': 'Кортрейк',
        'kv mechelen': 'Мехелен',
        'kv westerlo': 'Вестерло',
        'lahti': 'Лахти',
        'lambton jaffas': 'Лэмбтон Джаффас',
        'lamia': 'Ламия',
        'lazio': 'Лацио',
        'lech poznan': 'Лех Познань',
        'lech poznań': 'Лех Познань',
        'legia warsaw': 'Легия Варшава',
        'legia warszawa': 'Легия Варшава',
        'leixoes': 'Лейшойнш',
        'leixoes sc': 'Лейшойнш',
        'leixões': 'Лейшойнш',
        'levadeiakos': 'Левадиакос',
        'liverpool': 'Ливерпуль',
        'livingston': 'Ливингстон',
        'mafra': 'Мафра',
        'magic united tigers': 'Мэджик Юнайтед',
        'manchester city': 'Манчестер Сити',
        'manchester united': 'Манчестер Юнайтед',
        'mariehamn': 'Мариехамн',
        'maritimo': 'Маритиму',
        'marítimo': 'Маритиму',
        'mechelen': 'Мехелен',
        'medipol basaksehir': 'Медипол Башакшехир',
        'molenbeek': 'Молербек',
        'moreirense': 'Морейренсе',
        'moreton city excelsior': 'Мортон Сити',
        'motherwell': 'Мотеруэлл',
        'nacional': 'Насьонал',
        'nacional da madeira': 'Насьонал Мадейра',
        'napoli': 'Наполи',
        'newcastle jets (youth)': 'Ньюкасл Джетс мол.',
        'north eastern metrostars': 'Норт Истерн Метростарс',
        'north star': 'Норд Стар',
        'northern tigers': 'Нортерн Тайгерс',
        'nsw university': 'НСВ Университи',
        'ofi': 'ОФИ',
        'ofi crete': 'ОФИ Крит',
        'oh leuven': 'ОН Левен',
        'oliveira hospital': 'Оливейра Ошпитал',
        'oliveirense': 'Оливейренсе',
        'olympiacos': 'Олимпиакос',
        'olympiacos fc': 'Олимпиакос',
        'olympic fc': 'Олимпик ФК',
        'oud-heverlee leuven': 'ОН Левен',
        'pacos de ferreira': 'Пасуш де Феррейра',
        'pacos ferreira': 'Пасуш де Феррейра',
        'panathinaikos': 'Панатинаикос',
        'panathinaikos fc': 'Панатинаикос',
        'panetolikos': 'Панетоликос',
        'panserraikos': 'Пансерраикос',
        'paok': 'ПАОК',
        'paok thessaloniki': 'ПАОК Салоники',
        'para hills knights': 'Пара Хиллс Найтс',
        'paris saint-germain': 'ПСЖ',
        'pas lamia 1964': 'ПАС Ламия',
        'penafiel': 'Пенафиел',
        'pendikspor': 'Пендикспор',
        'peninsula power': 'Пенинсула Пауэр',
        'piast gliwice': 'Пяст Гливице',
        'playford city': 'Плейфорд Сити',
        'pogon szczecin': 'Погонь Щецин',
        'portimonense': 'Портимоненсе',
        'portimonense sc': 'Портимоненсе',
        'porto': 'Порту',
        'preston lions (u23)': 'Престон Лайонс до23',
        'psg': 'ПСЖ',
        'psv': 'ПСВ',
        'puszczka niepolomice': 'Пуща Неполомице',
        'queanbeyan city': 'Квинбиан Сити',
        'radomiak radom': 'Радомяк Радом',
        'rakow czestochowa': 'Ракув Ченстохова',
        'rakow częstochowa': 'Ракув Ченстохова',
        'rangers': 'Рейнджерс',
        'rc genk': 'Генк',
        'real madrid': 'Реал Мадрид',
        'real madrid cf': 'Реал Мадрид',
        'real sc': 'Реал',
        'real sport clube': 'Реал',
        'redlands united': 'Редлендс Юнайтед',
        'rio ave': 'Риу Аве',
        'rio ave fc': 'Риу Аве',
        'roma': 'Рома',
        'ross county': 'Росс Каунти',
        'royal antwerp': 'Антверпен',
        'royal union sg': 'Юнион Сент-Жилуаз',
        'rw dm': 'РВ ДМ',
        'sJK seinajoki': 'СЯК Сейняйоки',
        'samsunspor': 'Самсунспор',
        'sc braga': 'Брага',
        'sc covilha': 'Ковильян',
        'sc fafe': 'Фафе',
        'sc farense': 'Фаренсе',
        'sc oliveira hospital': 'Оливейра Ошпитал',
        'sc vilafranquense': 'Вилафранкенсе',
        'sevilla': 'Севилья',
        'sint-truiden': 'Синт-Трюйден',
        'sivasspor': 'Сивасспор',
        'sjk': 'СЯК',
        'sl benfica': 'Бенфика',
        'slask wroclaw': 'Сляск Вроцлав',
        'slask wrocław': 'Сляск Вроцлав',
        'south melbourne (w)': 'Саут Мельбурн ж',
        'sp covilha': 'Ковильян',
        'sporting': 'Спортинг',
        'sporting charleroi': 'Шарлеруа',
        'sporting covilha': 'Ковильян',
        'sporting cp': 'Спортинг',
        'st george willawong': 'Сент-Джордж Уиллавонг',
        'st johnstone': 'Сент-Джонстон',
        'st mirren': 'Сент-Миррен',
        'st truidense vv': 'Синт-Трюйден',
        'stal mielec': 'Сталь Мелец',
        'standard liege': 'Стандард Льеж',
        'standard liège': 'Стандард Льеж',
        'sunshine coast wanderers': 'Саншайн Кост',
        'sutherland sharks': 'Сазерленд Шаркс',
        'tondela': 'Тондела',
        'tottenham': 'Тоттенхэм',
        'trabzonspor': 'Трабзонспор',
        'trofense': 'Трофенсе',
        'ud oliveirense': 'Оливейренсе',
        'umraniyespor': 'Умраниеспор',
        'union saint-gilloise': 'Юнион Сент-Жилуаз',
        'uwa nedlands (w)': 'ЮВА Недлендс ж',
        'valencia': 'Валенсия',
        'valentine': 'Валентайн',
        'varzim': 'Варзин',
        'varzim sc': 'Варзин',
        'vilafranquense': 'Вилафранкенсе',
        'vitoria guimaraes': 'Витория Гимарайнш',
        'vitoria setubal': 'Витория Сетубал',
        'vitória guimarães': 'Витория Гимарайнш',
        'vitória setúbal': 'Витория Сетубал',
        'volos': 'Волос',
        'volos nfc': 'Волос',
        'vps': 'ВПС',
        'vps vaasa': 'ВПС Вааса',
        'west adelaide': 'Вест Аделаида',
        'westerlo': 'Вестерло',
        'western pride': 'Вестерн Прайд',
        'widzew lodz': 'Видзев Лодзь',
        'widzew łódź': 'Видзев Лодзь',
        'zaglebie lubin': 'Заглембе Любин',
        'zenit': 'Зенит',
        'zenit st. petersburg': 'Зенит',
        'ümraniyespor': 'Умраниеспор',
        'бавария (любители)': 'Бавария люб.',
        'белград аделаида': 'Белград Аделаида',
        'бокс хилл юнайтед (ж)': 'Бокс Хилл Юнайтед ж',
        'борундара иглс (ж)': 'Борундара Иглс ж',
        'боруссия (любители)': 'Боруссия люб.',
        'брисбен олимпик (до23)': 'Брисбен Олимпик до23',
        'брисбен роар': 'Брисбен Роар',
        'брисбен роар (мол)': 'Брисбен Роар мол.',
        'бродбич юнайтед (до23)': 'Бродбич Юнайтед до23',
        'валентайн': 'Валентайн',
        'вест аделаида': 'Вест Аделаида',
        'далвич хилл': 'Далвич Хилл',
        'интер лайонс': 'Интер Лайонс',
        'истерн сабербс (до23)': 'Истерн Сабёрбс до23',
        'канберра уайт иглз': 'Канберра Уайт Иглз',
        'кантербери банкстоун': 'Кантербери Банкстоун',
        'капалаба (до23)': 'Капалаба до23',
        'карролайн спрингс джордж кросс (до23)': 'Каролайн Спрингс до23',
        'квинбиан сити': 'Квинбиан Сити',
        'кемпбелтаун сити': 'Кемпбелтаун Сити',
        'лэмбтон джаффас': 'Лэмбтон Джаффас',
        'норд стар': 'Норд Стар',
        'норт истерн метростарс': 'Норт Истерн Метростарс',
        'нортерн тайгерс': 'Нортерн Тайгерс',
        'нсу университи': 'НСВ Университи',
        'ньюкасл джетс (мол)': 'Ньюкасл Джетс мол.',
        'пара хиллс найтс': 'Пара Хиллс Найтс',
        'пенинсула пауэр': 'Пенинсула Пауэр',
        'плейфорд сити': 'Плейфорд Сити',
        'престон лайонс (до23)': 'Престон Лайонс до23',
        'сазерленд шаркс': 'Сазерленд Шаркс',
        'саут мельбурн (ж)': 'Саут Мельбурн ж',
        'сент-джордж уиллавонг': 'Сент-Джордж Уиллавонг',
        'хейдельберг юнайтед (ж)': 'Хейдельберг Юнайтед ж',
        'хендэ (ж)': 'Хендэ ж',
        'херствиль': 'Херствиль',
        'хиллс юнайтед брамбис': 'Хиллс Юнайтед Брамбис',
        'централ коаст маринерс (мол)': 'Централ Коаст Маринерс мол.',
        'юва недлендс (ж)': 'ЮВА Недлендс ж',
    }
    return teams.get(name, name)
