# Словарь переводов команд на русский
TEAMS_RU = {
    # Финляндия
    'hjk helsinki': 'ХИК Хельсинки',
    'hjk': 'ХИК',
    'kups kuopio': 'КуПС Куопио',
    'kups': 'КуПС',
    'inter turku': 'Интер Турку',
    'ilves tampere': 'Ильвес Тампере',
    'ilves': 'Ильвес',
    'sJK seinajoki': 'СЯК Сейняйоки',
    'sjk': 'СЯК',
    'honka espoo': 'Хонка Эспоо',
    'honka': 'Хонка',
    'lahti': 'Лахти',
    'fc lahti': 'ФК Лахти',
    'mariehamn': 'Мариехамн',
    'ifk mariehamn': 'ИФК Мариехамн',
    'gnistan': 'Гнистан',
    'if gnistan': 'ИФ Гнистан',
    ' KTP': 'КТП',
    'fc KTP': 'ФК КТП',
    'vps vaasa': 'ВПС Вааса',
    'vps': 'ВПС',
    'fc haka': 'ФК Хака',
    'haka': 'Хака',
    
    # Польша
    'legia warsaw': 'Легия Варшава',
    'legia warszawa': 'Легия Варшава',
    'lech poznan': 'Лех Познань',
    'lech poznań': 'Лех Познань',
    'rakow czestochowa': 'Ракув Ченстохова',
    'rakow częstochowa': 'Ракув Ченстохова',
    'jagiellonia bialystok': 'Ягеллония Белосток',
    'jagiellonia białystok': 'Ягеллония Белосток',
    'slask wroclaw': 'Сляск Вроцлав',
    'slask wrocław': 'Сляск Вроцлав',
    'piast gliwice': 'Пяст Гливице',
    'widzew lodz': 'Видзев Лодзь',
    'widzew łódź': 'Видзев Лодзь',
    'pogon szczecin': 'Погонь Щецин',
    'cracovia krakow': 'Краковия Краков',
    'cracovia kraków': 'Краковия Краков',
    'gor zabrze': 'Гурник Забже',
    'gor nik zabrze': 'Гурник Забже',
    ' Warta poznan': 'Варта Познань',
    ' Warta poznań': 'Варта Познань',
    'radomiak radom': 'Радомяк Радом',
    'korona kielce': 'Корона Кельце',
    'puszczka niepolomice': 'Пуща Неполомице',
    'zaglebie lubin': 'Заглембе Любин',
    'zaglebie lubin': 'Заглембе Любин',
    'stal mielec': 'Сталь Мелец',
    'stal mielec': 'Сталь Мелец',
    
    # Турция
    'galatasaray': 'Галатасарай',
    'fenerbahce': 'Фенербахче',
    'fenerbahçe': 'Фенербахче',
    'besiktas': 'Бешикташ',
    'beşiktaş': 'Бешикташ',
    'trabzonspor': 'Трабзонспор',
    'basaksehir': 'Башакшехир',
    'medipol basaksehir': 'Медипол Башакшехир',
    'sivasspor': 'Сивасспор',
    'kayserispor': 'Кайсериспор',
    'antalyaspor': 'Антальяспор',
    'fraport taw antalyaspor': 'Фрапорт Тав Антальяспор',
    'kasimpasa': 'Касымпаша',
    'kasimpaşa': 'Касымпаша',
    'konyaspor': 'Коньяспор',
    'alanyaspor': 'Аланьяспор',
    'gaziantep fk': 'Газиантеп ФК',
    'hatayspor': 'Хатайспор',
    'istanbulspor': 'Стамбулспор',
    'ümraniyespor': 'Умраниеспор',
    'umraniyespor': 'Умраниеспор',
    'giresunspor': 'Гиресунспор',
    'pendikspor': 'Пендикспор',
    'fatih karagumruk': 'Фатих Карагюмрюк',
    'samsunspor': 'Самсунспор',
    'bodrumspor': 'Бодрумспор',
    'eyupspor': 'Эюпспор',
    'eyüpspor': 'Эюпспор',
    
    # Шотландия
    'celtic': 'Селтик',
    'rangers': 'Рейнджерс',
    'aberdeen': 'Абердин',
    'hearts': 'Хартс',
    'heart of midlothian': 'Харт оф Мидлотиан',
    'hibernian': 'Хиберниан',
    'hibs': 'Хибс',
    'dundee united': 'Данди Юнайтед',
    'dundee fc': 'Данди ФК',
    'motherwell': 'Мотеруэлл',
    'livingston': 'Ливингстон',
    'st mirren': 'Сент-Миррен',
    'st johnstone': 'Сент-Джонстон',
    'ross county': 'Росс Каунти',
    'kilmarnock': 'Килмарнок',
    
    # Бельгия
    'club brugge': 'Брюгге',
    'club brugge kv': 'Брюгге',
    'anderlecht': 'Андерлехт',
    'royal union sg': 'Юнион Сент-Жилуаз',
    'union saint-gilloise': 'Юнион Сент-Жилуаз',
    'royal antwerp': 'Антверпен',
    'antwerp': 'Антверпен',
    'gent': 'Гент',
    'kaa gent': 'Гент',
    'standard liege': 'Стандард Льеж',
    'standard liège': 'Стандард Льеж',
    'genk': 'Генк',
    'rc genk': 'Генк',
    'molenbeek': 'Молербек',
    'rw dm': 'РВ ДМ',
    'charleroi': 'Шарлеруа',
    'sporting charleroi': 'Шарлеруа',
    'mechelen': 'Мехелен',
    'kv mechelen': 'Мехелен',
    'cercle brugge': 'Серкль Брюгге',
    'cercle brugge ksv': 'Серкль Брюгге',
    'oh leuven': 'ОН Левен',
    'oud-heverlee leuven': 'ОН Левен',
    'kortrijk': 'Кортрейк',
    'kv kortrijk': 'Кортрейк',
    'sint-truiden': 'Синт-Трюйден',
    'st truidense vv': 'Синт-Трюйден',
    'westerlo': 'Вестерло',
    'kv westerlo': 'Вестерло',
    
    # Греция
    'olympiacos': 'Олимпиакос',
    'olympiacos fc': 'Олимпиакос',
    'panathinaikos': 'Панатинаикос',
    'panathinaikos fc': 'Панатинаикос',
    'aek athens': 'АЕК Афины',
    'aek athens fc': 'АЕК Афины',
    'paok thessaloniki': 'ПАОК Салоники',
    'paok': 'ПАОК',
    'aris thessaloniki': 'Арис Салоники',
    'aris': 'Арис',
    'volos nfc': 'Волос',
    'volos': 'Волос',
    'ofi crete': 'ОФИ Крит',
    'ofi': 'ОФИ',
    'lamia': 'Ламия',
    'pas lamia 1964': 'ПАС Ламия',
    'atromitos': 'Атромитос',
    'atromitos athens': 'Атромитос Афины',
    'asteras tripolis': 'Астерас Триполис',
    'asteras tripoli': 'Астерас Триполи',
    'panetolikos': 'Панетоликос',
    'levadeiakos': 'Левадиакос',
    'kifisia': 'Кифисья',
    'panserraikos': 'Пансерраикос',
    
    # Португалия
    'benfica': 'Бенфика',
    'sl benfica': 'Бенфика',
    'porto': 'Порту',
    'fc porto': 'Порту',
    'sporting cp': 'Спортинг',
    'sporting': 'Спортинг',
    'braga': 'Брага',
    'sc braga': 'Брага',
    'vitoria guimaraes': 'Витория Гимарайнш',
    'vitória guimarães': 'Витория Гимарайнш',
    'vitoria setubal': 'Витория Сетубал',
    'vitória setúbal': 'Витория Сетубал',
    'maritimo': 'Маритиму',
    'cs maritimo': 'Маритиму',
    'marítimo': 'Маритиму',
    'pacos ferreira': 'Пасуш де Феррейра',
    'pacos de ferreira': 'Пасуш де Феррейра',
    'fc pacos ferreira': 'Пасуш де Феррейра',
    'boavista': 'Боавишта',
    'boavista fc': 'Боавишта',
    'moreirense': 'Морейренсе',
    'fc moreirense': 'Морейренсе',
    'famalicao': 'Фамаликан',
    'fc famalicao': 'Фамаликан',
    'gil vicente': 'Жил Висенте',
    'gil vicente fc': 'Жил Висенте',
    'rio ave': 'Риу Аве',
    'rio ave fc': 'Риу Аве',
    'estoril': 'Эшторил',
    'gd estoril praia': 'Эшторил',
    'casa pia': 'Каза Пия',
    'casa pia ac': 'Каза Пия',
    'avess': 'Авеш',
    'av es': 'Авеш',
    'nacional': 'Насьонал',
    'cd nacional': 'Насьонал',
    'estrela amadora': 'Эштрела Амадора',
    'cf estrela amadora': 'Эштрела Амадора',
    'farense': 'Фаренсе',
    'sc farense': 'Фаренсе',
    'portimonense': 'Портимоненсе',
    'portimonense sc': 'Портимоненсе',
    'academica': 'Академика',
    'academica coimbra': 'Академика Коимбра',
    'tondela': 'Тондела',
    'cd tondela': 'Тондела',
    'chaves': 'Шавеш',
    'gd chaves': 'Шавеш',
    'penafiel': 'Пенафиел',
    'fc penafiel': 'Пенафиел',
    'leixoes': 'Лейшойнш',
    'leixões': 'Лейшойнш',
    'leixoes sc': 'Лейшойнш',
    'feirense': 'Фейренсе',
    'cd feirense': 'Фейренсе',
    'nacional da madeira': 'Насьонал Мадейра',
    'academico viseu': 'Академику Визеу',
    'académico de viseu': 'Академику Визеу',
    'vilafranquense': 'Вилафранкенсе',
    'sc vilafranquense': 'Вилафранкенсе',
    'mafra': 'Мафра',
    'cd mafra': 'Мафра',
    'oliveirense': 'Оливейренсе',
    'ud oliveirense': 'Оливейренсе',
    'trofense': 'Трофенсе',
    'cd trofense': 'Трофенсе',
    'covilha': 'Ковильян',
    'sc covilha': 'Ковильян',
    'sp covilha': 'Ковильян',
    'varzim': 'Варзин',
    'varzim sc': 'Варзин',
    'fafe': 'Фафе',
    'sc fafe': 'Фафе',
    'oliveira hospital': 'Оливейра Ошпитал',
    'sc oliveira hospital': 'Оливейра Ошпитал',
    'real sc': 'Реал',
    'real sport clube': 'Реал',
    'estrela': 'Эштрела',
    'cf estrela': 'Эштрела',
    'sp covilha': 'Ковильян',
    'sporting covilha': 'Ковильян',
}

def translate_team(name):
    """Переводит название команды на русский"""
    if not name:
        return name
    name_lower = name.lower().strip()
    return TEAMS_RU.get(name_lower, name)

def translate_match(home, away):
    """Переводит названия обеих команд"""
    return translate_team(home), translate_team(away)
